version: "3"

services:
    db: 
        image: mysql:5.6 
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root            
        volumes:
            - ./data:/docker-entrypoint-initdb.d
    backend:
        build: autism-backend/.
        env_file:
            - autism-backend/.env_prod
        ports:
            - "8080:8080"
        depends_on:
            - db
    frontend:
        build: autism-app/.
        ports:
            - "3000:3000"
 

