version: "3"
services:
    db: 
        image: mysql:5.5 
        ports:
            - "3306:3306"
        environment : 
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - ./data:/docker-entrypoint-initdb.d
